version: '3'
services:
  front-end:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./node_modules:/front-end/node_modules
      - ./:./front-end
    ports:
      - "3000:3000"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - back-end
  # back-end:
  #   image: node:12
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: sh -c "cd back-end && npm install && npm start"